from pathlib import Path
from html import escape
import base64,re,json,zipfile
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'public'
projects=[
('sala-amarela','Sala Amarela','Proteção e acolhimento','Espaço de escuta especializada na delegacia, descrito no material como atendimento a mulheres e crianças vítimas de violência.'),
('coord-mulher','Coordenadoria da Mulher','Proteção e acolhimento','Estrutura de acolhimento, orientação e apoio às mulheres apresentada no documento biográfico.'),
('sala-lilas','Sala Lilás','Proteção e acolhimento','Atendimento e orientação a pessoas idosas, com escuta e apoio relacionados a seus direitos, segundo o material.'),
('abrigo','Abrigo Bom Samaritano','Proteção e acolhimento','Serviço descrito como acolhimento provisório para pessoas em situação de vulnerabilidade social.'),
('casa-mulher','Casa da Mulher Oriximinense','Proteção e acolhimento','Espaço voltado ao atendimento e à autonomia das mulheres, conforme a descrição do documento.'),
('cadunico','Cadastro Único','Estrutura e serviços','O material registra a reorganização do espaço de atendimento do Cadastro Único em Oriximiná.'),
('assistencia','Assistência Social','Estrutura e serviços','Registro do prédio da Assistência Social e de mudanças na estrutura de atendimento municipal.'),
('cras','CRAS Cidade Nova','Estrutura e serviços','Unidade de referência da assistência social citada no documento entre as estruturas de atendimento às famílias.'),
('anita','Centro de Convivência Anita Valente','Estrutura e serviços','Equipamento de convivência citado no material biográfico, com registro de sua estrutura física.'),
('paa','Programa de Aquisição de Alimentos','Educação e inclusão','O PAA é apresentado no documento em relação à produção local e à oferta de alimentos a famílias em situação de vulnerabilidade.'),
('pai','Alfabetização de Adultos e Idosos','Educação e inclusão','O projeto PAI é descrito como uma iniciativa de acesso à educação para pessoas adultas e idosas.'),
('marcha','Marcha das Mulheres','Educação e inclusão','Registro de mobilização relacionada aos direitos das mulheres, incluído no material biográfico.')]
gallery=[('familia','Registro familiar','Vida pessoal'),('policia','Trajetória na Polícia Civil','Trajetória'),('equipe-rosa','Equipe da assistência social','Trajetória'),('mulher-destaque','Mulher Destaque · 2023','Reconhecimentos'),('gesuas','Desafio GESUAS','Reconhecimentos'),('premio-cnas','Prêmio CNAS Simone Albuquerque','Reconhecimentos'),('mocao','Moção de Aplausos e Louvor · 2025','Reconhecimentos'),('renata-diploma','Registro de homenagem','Reconhecimentos')]
cards='\n'.join(f'''<article class="project-card reveal" data-category="{cat}"><button class="photo-button" data-photo="assets/{file}.webp" data-caption="{escape(title)} — material biográfico, página 2" aria-label="Ampliar imagem: {escape(title)}"><img src="assets/{file}.webp" alt="Registro de {escape(title)} no documento biográfico" width="527" height="338" loading="lazy"><span class="expand" aria-hidden="true">↗</span></button><div class="project-copy"><span class="eyebrow">{cat}</span><h3>{title}</h3><p>{body}</p></div></article>''' for file,title,cat,body in projects)
photos='\n'.join(f'''<figure class="archive-item"><button class="photo-button" data-photo="assets/{file}.webp" data-caption="{escape(title)} — acervo do material biográfico" aria-label="Ampliar imagem: {escape(title)}"><img src="assets/{file}.webp" alt="{escape(title)}" width="470" height="338" loading="lazy"><span class="expand" aria-hidden="true">↗</span></button><figcaption><span>{cat}</span><strong>{title}</strong></figcaption></figure>''' for file,title,cat in gallery)
html='''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142cad"><title>Renata Fonseca | História e trajetória</title><meta name="description" content="Um registro biográfico de Renata Fonseca: formação, trajetória profissional, iniciativas em Oriximiná e acervo fotográfico."><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip-link" href="#conteudo">Pular para o conteúdo</a><div class="reading-progress" aria-hidden="true"></div>
<header class="header"><a class="wordmark" href="#inicio" aria-label="Renata Fonseca — início">renata<span>fonseca.</span></a><nav class="desktop-nav" aria-label="Navegação principal"><a href="#sobre">Sobre</a><a href="#trajetoria">Trajetória</a><a href="#iniciativas">Iniciativas</a><a href="#acervo">Acervo</a></nav><a class="header-link" href="#fontes">Sobre este acervo <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></header>
<div id="mobile-menu" class="mobile-menu" hidden><nav aria-label="Navegação móvel"><a href="#sobre">Sobre</a><a href="#trajetoria">Trajetória</a><a href="#iniciativas">Iniciativas</a><a href="#reconhecimentos">Reconhecimentos</a><a href="#acervo">Acervo</a><a href="#fontes">Fontes</a></nav><p>Renata Fonseca · Acervo biográfico</p></div>
<main id="conteudo"><section class="hero" id="inicio" aria-labelledby="hero-title"><div class="hero-type"><span class="eyebrow light">ACERVO BIOGRÁFICO &nbsp; / &nbsp; ORIXIMINÁ, PARÁ</span><h1 id="hero-title">Renata<br><em>Fonseca.</em></h1><p>História pessoal.<br>Trajetória profissional.<br>Registros de uma vida pública.</p><a class="button button-light" href="#sobre">Conheça a trajetória <span aria-hidden="true">↓</span></a><div class="hero-foot"><span>UM OLHAR SOBRE SUA HISTÓRIA</span><span>01 — 06</span></div></div><figure class="hero-photo"><img src="assets/retrato.webp" alt="Retrato de Renata Fonseca, com blusa verde, extraído do material biográfico" width="900" height="1080" fetchpriority="high"><figcaption>RENATA FONSECA <span>Acervo pessoal · material biográfico</span></figcaption></figure><span class="hero-side" aria-hidden="true">HISTÓRIA & MEMÓRIA</span></section>
<section class="section about" id="sobre"><div class="section-marker"><span>01 / SOBRE</span><span>UMA APRESENTAÇÃO</span></div><div class="about-grid"><h2 class="reveal">Uma história,<br><em>muitos capítulos.</em></h2><div class="about-copy reveal"><p class="lead">Da experiência na indústria ao serviço público, o material biográfico reúne diferentes momentos da trajetória de Renata Fonseca.</p><p>O documento a apresenta como formada em Administração Pública, pós-graduada em Segurança Pública e com atuação na Polícia Civil do Pará e na assistência social de Oriximiná.</p><p>No âmbito familiar, registra que é mãe de Guilherme e esposa de Delegado Fonseca. A relação com Oriximiná aparece tanto nos registros pessoais quanto nas atividades profissionais descritas.</p><a class="text-link" href="#trajetoria">Explore os capítulos <span aria-hidden="true">↗</span></a></div></div><div class="fact-strip"><div><span>FORMAÇÃO</span><strong>Administração Pública</strong></div><div><span>ESPECIALIZAÇÃO</span><strong>Segurança Pública</strong></div><div><span>LOCAL DE ATUAÇÃO CITADO</span><strong>Oriximiná · Pará</strong></div></div></section>
<section class="section journey" id="trajetoria"><div class="section-marker"><span>02 / TRAJETÓRIA</span><span>PERCURSOS PROFISSIONAIS</span></div><div class="journey-grid"><div class="journey-intro"><h2>Os caminhos<br>da <em>trajetória.</em></h2><p>Experiências e formação registradas no documento de referência.</p><p class="source-note">O material não informa as datas dessas etapas. A sequência abaixo é temática e não estabelece uma cronologia comprovada.</p><figure class="journey-photo"><img src="assets/policia.webp" alt="Renata em registro com profissionais da Polícia Civil" width="735" height="413" loading="lazy"><figcaption>Registro profissional · acervo biográfico</figcaption></figure></div><ol class="timeline"><li class="reveal"><span class="step">01</span><div><span class="eyebrow">EXPERIÊNCIA NA INDÚSTRIA</span><h3>Moto Honda da Amazônia</h3><p>A empresa aparece entre as experiências profissionais apresentadas no material. Cargo e período não são especificados.</p></div></li><li class="reveal"><span class="step">02</span><div><span class="eyebrow">FORMAÇÃO ACADÊMICA</span><h3>Administração Pública</h3><p>Graduação informada no documento biográfico. A instituição e o ano de conclusão não são indicados.</p></div></li><li class="reveal"><span class="step">03</span><div><span class="eyebrow">PÓS-GRADUAÇÃO</span><h3>Segurança Pública</h3><p>Especialização citada no material como parte de sua formação profissional.</p></div></li><li class="reveal"><span class="step">04</span><div><span class="eyebrow">SERVIÇO PÚBLICO</span><h3>Polícia Civil do Pará</h3><p>O documento menciona concurso da Polícia Civil e atuação como investigadora em Oriximiná, ao lado de Delegado Fonseca.</p></div></li><li class="reveal"><span class="step">05</span><div><span class="eyebrow">GESTÃO MUNICIPAL</span><h3>Assistência social em Oriximiná</h3><p>O material registra atuação à frente da Secretaria de Assistência Social. Não informa o período do exercício da função.</p></div></li></ol></div></section>
<section class="section initiatives" id="iniciativas"><div class="section-marker"><span>03 / INICIATIVAS</span><span>REGISTROS EM ORIXIMINÁ</span></div><div class="section-heading"><h2>Serviços, espaços<br>e <em>iniciativas.</em></h2><p>Uma consulta aos equipamentos e projetos descritos no material biográfico. Os registros não confirmam a situação atual dos serviços nem atribuem sua realização exclusivamente a uma pessoa.</p></div><div class="filters" role="group" aria-label="Filtrar iniciativas por tema"><button class="filter active" data-filter="all" aria-pressed="true">Todos <span>12</span></button><button class="filter" data-filter="Proteção e acolhimento" aria-pressed="false">Proteção e acolhimento</button><button class="filter" data-filter="Estrutura e serviços" aria-pressed="false">Estrutura e serviços</button><button class="filter" data-filter="Educação e inclusão" aria-pressed="false">Educação e inclusão</button></div><p class="filter-status" aria-live="polite" aria-atomic="true">12 registros no acervo</p><div class="project-grid">__PROJECTS__</div></section>
<section class="section recognition" id="reconhecimentos"><div class="section-marker"><span>04 / RECONHECIMENTOS</span><span>MEMÓRIA DOCUMENTAL</span></div><div class="recognition-grid"><div><h2>Homenagens<br>e <em>registros.</em></h2><p>Reconhecimentos mencionados no documento de referência. Datas e entidades são apresentadas apenas quando constam no material.</p></div><div class="award-list"><article class="award reveal"><span>2023</span><div><h3>Prêmio Mulher Destaque</h3><p>Câmara Municipal de Oriximiná.</p></div></article><article class="award reveal"><span>2025</span><div><h3>Moção de Aplausos e Louvor</h3><p>Poder Legislativo de Óbidos.</p></div></article><article class="award reveal"><span>SEM DATA</span><div><h3>Prêmio CNAS Simone Albuquerque</h3><p>Reconhecimento relacionado à assistência social, citado no material.</p></div></article><article class="award reveal"><span>SEM DATA</span><div><h3>Desafio GESUAS</h3><p>Registro relacionado à gestão da assistência social.</p></div></article><article class="award reveal"><span>SEM DATA</span><div><h3>Títulos de cidadania</h3><p>O documento informa os títulos de Cidadã Paraense e Cidadã Oriximinaense.</p></div></article></div></div></section>
<section class="section archive" id="acervo"><div class="section-marker"><span>05 / ACERVO</span><span>FOTOGRAFIAS & MEMÓRIA</span></div><div class="section-heading"><h2>A história<br><em>em imagens.</em></h2><p>Registros familiares, profissionais e de homenagens. Selecione uma fotografia para ampliar.</p></div><div class="archive-grid">__GALLERY__</div></section>
<section class="section sources" id="fontes"><div class="section-marker"><span>06 / FONTES</span><span>SOBRE ESTE ACERVO</span></div><div class="sources-grid"><h2>De onde vêm<br><em>os registros.</em></h2><div><p class="lead">Este site organiza informações e imagens do material biográfico compartilhado para este projeto.</p><details open><summary>Documento de referência <span aria-hidden="true">+</span></summary><p><strong>biografia-renata-fonseca-web.pdf</strong>, 2 páginas. A página 1 reúne o retrato e os reconhecimentos; a página 2 apresenta formação, experiências profissionais e iniciativas.</p></details><details><summary>Critérios de edição <span aria-hidden="true">+</span></summary><p>Textos resumidos em linguagem informativa. As alegações do material são atribuídas à fonte, sem verificação independente. Não foram acrescentadas datas, indicadores de impacto, cargos atuais ou informações de atendimento ausentes do documento.</p></details><details><summary>Fotografias e publicações <span aria-hidden="true">+</span></summary><p>As fotografias foram recuperadas dos arquivos fornecidos para o projeto, com origem no material biográfico. A resolução disponível limita a ampliação. Não foram importados vídeos ou novas publicações do Instagram.</p></details><a class="text-link" href="https://www.instagram.com/renata.fonseca.oficial/" target="_blank" rel="noopener noreferrer">Consultar perfil de referência no Instagram <span aria-hidden="true">↗</span></a></div></div></section>
</main><footer><a class="wordmark" href="#inicio">renata<span>fonseca.</span></a><p>História e trajetória<br><span>Acervo biográfico · edição de setembro de 2026</span></p><a href="#inicio" class="back-top">Voltar ao início <span aria-hidden="true">↑</span></a></footer>
<dialog id="lightbox" aria-labelledby="lightbox-caption"><div class="lightbox-toolbar"><span>ACERVO FOTOGRÁFICO</span><button class="close-lightbox" aria-label="Fechar fotografia">×</button></div><img id="lightbox-image" alt=""><div class="lightbox-bottom"><button class="previous-photo" aria-label="Fotografia anterior">←</button><p id="lightbox-caption"></p><button class="next-photo" aria-label="Próxima fotografia">→</button></div><p class="lightbox-hint">Use as setas para navegar e Esc para fechar.</p></dialog></body></html>'''.replace('__PROJECTS__',cards).replace('__GALLERY__',photos)
P.joinpath('index.html').write_text(html)
print('Built index.html with',len(projects),'initiatives and',len(gallery),'archive photographs')
